# Generated by Django 4.2.5 on 2023-09-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marka', models.CharField(max_length=64)),
                ('Model', models.CharField(max_length=64)),
                ('Agırlık', models.FloatField()),
                ('Kategori', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('kirayan_uye', models.CharField(max_length=100)),
                ('iha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iha_info', to='iha.iha')),
            ],
        ),
    ]
