# Generated by Django 4.2.5 on 2023-09-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iha', '0002_remove_iha_agırlık_remove_iha_kategori_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iha',
            old_name='Kanat_acıklıgı',
            new_name='Kanat_açıklığı',
        ),
        migrations.RenameField(
            model_name='iha',
            old_name='Maksimum_kalkıs_agırlıgı',
            new_name='Maksimum_kalkış_ağırlığı',
        ),
    ]
