# Generated by Django 4.2.5 on 2023-09-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iha', '0003_rename_kanat_acıklıgı_iha_kanat_açıklığı_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iha',
            old_name='Havada_kalma_suresi',
            new_name='Havada_kalma_süresi',
        ),
        migrations.RenameField(
            model_name='kira',
            old_name='kirayan_uye',
            new_name='kirayan_üye',
        ),
    ]
