# Generated by Django 4.2.5 on 2023-09-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iha', '0004_rename_havada_kalma_suresi_iha_havada_kalma_süresi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kira',
            name='Adet',
            field=models.IntegerField(default=0),
        ),
    ]
