# Generated by Django 4.2.5 on 2023-09-17 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iha', '0007_rename_rentalhistory_kiralıktarihi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KiralıkTarihi',
            new_name='RentalHistory',
        ),
        migrations.AlterField(
            model_name='kira',
            name='iha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iha_rentalhistory', to='iha.iha'),
        ),
    ]
